{application,test_appl,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{test_appl_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[test_appl,test_appl_app,test_appl_sup]},
              {licenses,["Apache-2.0"]},
              {links,[]}]}.
